/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package edu.vu

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'edu.vu.sample-plugin'.
 */
class SamplePluginTest {
    @Test fun `sample-plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("edu.vu.sample-plugin")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
